{% set name = "chgnet" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CederGroupHub/chgnet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6a5656b93383988a338bfbae0270f97b69dce2704785efa942b0243c3abc847f

build:
  skip: true  # [py<310]
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - setuptools >=65.0
    - wheel
    - pip
    - numpy
  run:
    - typing-extensions >=4.12
    - python
    - ase >=3.23.0
    - cython >=3
    - numpy
    - nvidia-ml >=7.352.0
    - pymatgen >=2024.9.10
    - pytorch >=2.4.1

test:
  imports:
    - chgnet

about:
  home: https://github.com/CederGroupHub/chgnet
  summary: Pretrained Universal Neural Network Potential for Charge-informed Atomistic Modeling
  dev_url: https://github.com/CederGroupHub/chgnet
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
