{% set name = "chgnet" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CederGroupHub/chgnet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7acbf4ee21bfa98bcf88272d0369e6c9c60c92c254fa7b96d9521bd3a8f1af72

build:
  skip: true  # [py<39]
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - setuptools >=65.0
    - wheel
    - pip
  run:
    - python
    - ase >=3.23.0
    - cython >=3
    - numpy >=1.26
    - nvidia-ml >=7.352.0
    - pymatgen >=2023.10.11
    - pytorch >=1.11.0

test:
  imports:
    - chgnet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CederGroupHub/chgnet
  summary: Pretrained Universal Neural Network Potential for Charge-informed Atomistic Modeling
  dev_url: https://github.com/CederGroupHub/chgnet
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
