{% set name = "chgnet" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CederGroupHub/chgnet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 46621c74174feb434c3f5204c4718658f53fabf78a8d5bc2e16a755f23e5b8d4

build:
  skip: true  # [py<39]
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - setuptools >=65.0
    - wheel
    - pip
    - numpy
  run:
    - typing-extensions >=4.12
    - python
    - ase >=3.23.0
    - cython >=3
    - numpy
    - nvidia-ml >=7.352.0
    - pymatgen >=2024.9.10
    - pytorch >=2.4.1

test:
  imports:
    - chgnet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CederGroupHub/chgnet
  summary: Pretrained Universal Neural Network Potential for Charge-informed Atomistic Modeling
  dev_url: https://github.com/CederGroupHub/chgnet
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
